#top level Mesa model/initial skeleton, monthly cycle
import yaml
import numpy as np
from mesa import Model
from mesa.datacollection import DataCollector

from housing_abm.agents.renter import Renter

class AtlantaHousingModel(Model):
    def __init__(self, config_path: str = "config/baseline_params.yaml",
                policy_paths: list[str] | None = None, seed: int | None = None,
                n_households: int | None = None):
        super().__init__(seed=seed)
        with open(config_path) as f:
            self.params = yaml.safe_load(f) #take parameters from given config path

        self_policies = []  
        for path in (policy_paths or []): #take policies if given
            with open(path) as f:
                self_policies.append(yaml.safe_load(f))
        
        self.random_gen = np.random.default_rng(seed=seed)
        self.current_month = 0
        #placeholder exogenous interest rate
        #TODO: swap for real series per month
        self.current_fed_rate_annual = 0.039
        self.current_fed_rate_monthly = self.current_fed_rate_annual / 12
        #different types of mortgages
        self.mortgage_terms = {"fha": {}, "conventional" : {}, "investor_dscr": {}}
        with open("config/mortgage_terms.yaml") as f:
            self.mortgage_terms = yaml.safe_load(f)
        
        self.datacollector = DataCollector( #placeholder data collector 
            model_reporters = { #model level data
                "n_agents": lambda m: len(m.agents),
                "n_renting": lambda m: m._n_renting(),
                "mean_bank_balance": lambda m: m._mean_bank_balance(),
                #TODO: add real core indicators once agent pop. implemented
                #"homeownership_rate", "investor_purchase_share",
                #rental_vacancy_rate". "median rent", "transaction_volume"
            }
        )
        #create initial renter population
        #TODO: replace placeholder income with real calibrated
        n_households = n_households or self.params.get("n_households", 100)
        for _ in range(n_households):
            income = float(self.random_gen.lognormal(mean = 10.5, sigma = 0.6)) #realistic terms, generated by Claude
            age = int(self.random_gen.integers(22,65))
            Renter(model=self, income = income, age = age, tract_id="tract_001") #default initialization

    def step(self):
        self.current_month += 1
        #TODO: implement remaining phases of monthly cycle
        #construction, market clearing, policy updates
        #schedule.step currently only runs each agent's step 
        #for renter just does consumption without market
        self.agents.shuffle_do("step")
        self.datacollector.collect(self)


    #core indicator reporters
    def _n_renting(self):
        return sum(1 for agent in self.agents if getattr(agent, "status", None) == "renting") #checks status attritbute for renters

    def _mean_bank_balance(self):
        balances = [agent.bank_balance for agent in self.agents]
        return float(np.mean(balances)) if balances else 0 #if balances exist, return mean as float
    
    #stubs for market clearing

    def _homeownership_rate(self):
        raise NotImplementedError
    
    def _investor_purchase_share(self):
        raise NotImplementedError
    
    def _rental_vacancy_rate(self):
        raise NotImplementedError

    def _median_rent(self):
        raise NotImplementedError

    def _transaction_volume(self):
        raise NotImplementedError
    

    #placeholder hooks
    def queue_housing_decision(self,agent): #mark and queue an agent for the housing-market process
        pass #TODO

    def exit_tract(self, agent): #remove agent from schedule 
        pass #TODO

