#top level Mesa model/initial skeleton, monthly cycle
import yaml
import numpy as np
from mesa import Model
from mesa.datacollection import DataCollector

from housing_abm.agents.first_time_buyer import FirstTimeBuyer
from housing_abm.agents.renter import Renter
from housing_abm.markets.ownership_market import generate_placeholder_sale_stock, run_ownership_market
from housing_abm.markets.rental_market import generate_placeholder_rental_stock, run_rental_market
from housing_abm.tract import Tract

class AtlantaHousingModel(Model):
    def __init__(self, config_path: str = "config/baseline_params.yaml",
                policy_paths: list[str] | None = None, seed: int | None = None,
                n_households: int | None = None):
        super().__init__(seed=seed)
        with open(config_path) as f:
            self.params = yaml.safe_load(f) #take parameters from given config path

        self_policies = []  
        for path in (policy_paths or []): #take policies if given
            with open(path) as f:
                self_policies.append(yaml.safe_load(f))
        
        self.random_gen = np.random.default_rng(seed=seed)
        self.current_month = 0
        #placeholder exogenous interest rate
        #TODO: swap for real series per month
        self.current_fed_rate_annual = 0.039
        self.current_fed_rate_monthly = self.current_fed_rate_annual / 12
        #different types of mortgages
        self.mortgage_terms = {"fha": {}, "conventional" : {}, "investor_dscr": {}}
        with open("config/mortgage_terms.yaml") as f:
            self.mortgage_terms = yaml.safe_load(f)


        self.tracts = {"tract_001": Tract("tract_001")} #placeholder storage of tracts


        #queue of renters in social housing looking to rent again
        #-queue housing decision(), drained by run_rental_market() in step()

        self._rental_bid_queue = []
        self._ownership_bid_queue = []

        
        self.datacollector = DataCollector( #placeholder data collector 
            model_reporters = { #model level data
                "n_agents": lambda m: len(m.agents),
                "n_renting": lambda m: m._n_renting(),
                "n_owning": lambda m: sum(1 for agent in m.agents if getattr(agent, "status", None) == "owning"),
                "mean_bank_balance": lambda m: m._mean_bank_balance(),
                "rental_vacancy_rate": lambda m: m._rental_vacancy_rate(),  
                "homeownership_rate": lambda m: m._homeownership_rate(),
                #TODO: add real core indicators once agent pop. implemented
                #"investor_purchase_share",
                #"median rent", "transaction_volume"
            }
        )
        #create initial renter population
        #TODO: replace placeholder income with real calibrated
        n_households = n_households or self.params.get("n_households", 100)
        for _ in range(n_households):
            income = float(self.random_gen.lognormal(mean = 9.4, sigma = 0.55)) #realistic terms, generated by Claude - average ~$2,980 per month
            age = int(self.random_gen.integers(22,65))
            Renter(model=self, income = income, age = age, tract_id="tract_001") #default initialization

        
        #placholder exogenous rental stock 
        self.rental_units = generate_placeholder_rental_stock(self)
        self.for_sale_units = generate_placeholder_sale_stock(self)

       

    def step(self):
        self.current_month += 1
        #TODO: implement remaining phases of monthly cycle
        #construction, market clearing, policy updates
        #shuffle_do currently only runs each agent's step 
        #for renter just does consumption without market
        self.agents.shuffle_do("step")
        #match queued renters against vacant rental stock

        run_ownership_market(self) #buyers get first chance

        run_rental_market(self)

        self.datacollector.collect(self)
        


    #core indicator reporters
    def _n_renting(self):
        return sum(1 for agent in self.agents if getattr(agent, "status", None) == "renting") #checks status attritbute for renters

    def _mean_bank_balance(self):
        balances = [agent.bank_balance for agent in self.agents if hasattr(agent, "bank_balance")]#only applies to household agents
        return float(np.mean(balances)) if balances else 0 #if balances exist, return mean as float
    

    def _homeownership_rate(self):
        owners = sum(1 for agent in self.agents if getattr(agent, "status", None) == "owning")
        total = len([agent for agent in self.agents if hasattr(agent, "income")])
        return owners / total if total > 0 else 0.0
    
    def _investor_purchase_share(self):
        raise NotImplementedError
    
    def _rental_vacancy_rate(self):
        vacant = sum(1 for unit in self.rental_units if unit.tenant is None and unit.on_rental_market)
        total = len(self.rental_units)
        return vacant / total if self.rental_units else 0.0

    def _median_rent(self):
        raise NotImplementedError

    def _transaction_volume(self):
        raise NotImplementedError
    
    #tract/quality getters
    def quality_affordable(self, price, tract_id): #given price, what quality can you afford
        tract = self.tracts[tract_id]
        return price/tract.price_per_quality
    
    def market_rent_for_quality(self, quality, tract_id): #given quality, what rent is it at a tract level
        tract = self.tracts[tract_id]
        return quality *tract.rent_per_quality

    def monthly_payment(self, principal, i_r_monthly, term_months): #monthly payment calculation
        if principal <= 0:
            return 0.0
        annuity_factor = (1- (1+i_r_monthly)**(-term_months))/i_r_monthly
        return principal / annuity_factor
    
    def ftb_income_cutoff(self, floor_share_p_floor):
        incomes = [agent.income for agent in self.agents if hasattr(agent, "income")] #filter out houses 
        return float(np.quantile(incomes, floor_share_p_floor)) if incomes else 0.0 #return the income you need to be above the cutoff

    #placeholder hooks
    def queue_housing_decision(self,agent):
         #mark and queue an agent in social housing for the housing-market process
        if isinstance(agent, Renter): #seeing if can become first time buyer
            if self.for_sale_units:#available houses
                min_price = min(u.price for u in self.for_sale_units)
                min_down = self.mortgage_terms["fha"]["min_down_payment_pct"]*min_price #loan regulation check
                if agent.bank_balance >= min_down: #has enough money
                    self._promote_to_first_time_buyer(agent)
                    return
        if agent not in self._rental_bid_queue: #everyone else
            self._rental_bid_queue.append(agent)

    def exit_tract(self, agent): #remove agent from schedule 
        #occurs if rent burden became high or they moved away
        #vacate unit if exists, then remove from market
        if agent.house is not None:
            agent.house.tenant = None
            agent.house.on_rental_market = True
            agent.house = None
        if agent in self._rental_bid_queue:
            self._rental_bid_queue.remove(agent)
        agent.remove()

    def queue_rental_bid(self, agent, fraction_of_income: float = 0.33):
        agent.rent_affordability_fraction = fraction_of_income #how much of their income do they bid for rent
        self.queue_housing_decision(agent)
    
    def queue_ownership_bid(self, agent, max_price: float, down_payment: float): #creates a bid
        self._ownership_bid_queue.append(
            {"agent": agent, "max_price": max_price, "down_payment": down_payment}
        )

    def _promote_to_first_time_buyer(self, renter): #promote when a renter has enough money for a down payment on a house
        #create new FTB agent, delete the old renter agent
        ftb = FirstTimeBuyer(model = self, income= renter.income, age=renter.age, tract_id = renter.tract_id)
        ftb.bank_balance = renter.bank_balance
        ftb.desired_balance = renter.desired_balance

        renter.remove() 



